### ISSUE TITLE
Notebooks not currently building on mybinder.org

### ISSUE THREAD

**Issue by jezcope** [datacite/notebooks#9]
Hi folks, both Frances and I tried to load up the Binder link today and it failed to build for either of us. More specifically, it looks like the C component of the igraph module is failing for some reason. Full build log here:

https://gist.github.com/jezcope/e0b558756e3c82097679e9445f45ffc3

**Comment by almereyda** [comment]
Same here.

**Comment by jezcope** [comment]
I think I have this fixed: pull request on the way soon.
